version: '3.6'

services: 
  flexxusapp:
    image: fabreguesm/flexxusapp:1.136.6
    ports: 
      - '5005:80'
    networks:
      - traefik      
    deploy:      
      placement:
        constraints: ["${NODE}"]            
    environment:
      - MAIL_TO_ERROR=errores.flexxus@gmail.com
      - URL_MAP_SERVICE=http://10.150.4.12:15310
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}  
networks:
  traefik:
    external: true  
    name: traefik
